### ISSUE TITLE
Move repository to rust-lang

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/areweasyncyet.rs#27]
Hello, the current `rustasync` organisation is considered deprecated, and the Rust Programming Language organisation is trying to consolidate managing Rust's GitHub organisations, as such we'd like you to consider moving your repository to the main `rust-lang` organisation instead.

## How Do I Move To `rust-lang`?

You won't be able to transfer your repository directly, you'll need to transfer your repository to @Mark-Simulacrum, who will then move your repository to the `rust-lang` organisation. They will also be able to assist with joining the organization if you aren't a member already.

cc/ @upsuper

**Comment by Mark-Simulacrum** [comment]
We also need to know:
 * what Rust teams need access (if any)?
 * who else needs access, and at what level (write or admin)?

**Comment by upsuper** [comment]
I would like to keep my access to this repo, and I don't think I'm member of rust-lang org currently.

**Comment by Mark-Simulacrum** [comment]
I will make sure we invite you as part of the process, then.

**Comment by nikomatsakis** [comment]
@Mark-Simulacrum I think this will be part of the Async Foundations WG "ambit", but I think the team repo kind of needs to be "re-sync'd" here, I don't know that there's a corresponding, up-to-date github team to use. That WG is mostly a lang/compiler effort so I would think that those two teams could have access, although I really doubt anyone not from the WG will be doing any updating (and @upsuper of course should also have access!).

**Comment by yoshuawuyts** [comment]
A thing to note here is that the website seems to be hosted from `gh-pages`. This means that if we initiate the transfer, the actual site might go down as the url no longer resolves. To that extent we should probably coordinate when to transfer this.

The steps are:
1. I transfer this repo to myself
2. I initiate the transfer request to @Mark-Simulacrum 
3. The request is accepted, and @Mark-Simulacrum now moves the repo to `rust-lang`
4. @alexcrichton updates our DNS provider to point to the new url

I propose we do this next week Tuesday. Can everyone tagged review this plan, and confirm this works for them? If so, I propose we do this around 6pm UTC so everyone involved will be awake, and hopefully things can go mostly smoothly. How does this sound?

**Comment by upsuper** [comment]
I'm not sure if there is anything need to be done in the DNS side, because we are using A records for the site, and I don't think there is any other authentication... That said, it seems the domain is still using istanco's DNS, which itself should probably be switched?

**Comment by Mark-Simulacrum** [comment]
Looks like I have the necessary permissions, thanks @yoshuawuyts! I will proceed with the move on Tuesday as you've sadi to give time for people to give feedback and also to try and ensure we have folks on hand to fix things if this does cause breakage.

re:DNS, it seems like we can handle that separately (@alexcrichton is the best point of contact) and get it moved over when you're ready.

**Comment by alexcrichton** [comment]
For DNS updates the actual DNS servers are somewhere that I do not host or manage, so if you'd like to update/move DNS I'll need to get the current DNS configuration to move it over to our AWS account for DNS hosting, and then it can be tweaked.

**Comment by upsuper** [comment]
Hmmm, I have no access to the DNS configuration anymore from my original account. I suppose that it should be configurable via Rust's team's registrar?

**Comment by alexcrichton** [comment]
We do not have access to DNS records, our hosting just points to nameservers elsewhere. Do you have a copy of what records you'd like to create?

**Comment by upsuper** [comment]
I think the only records we need are A records on the top level domain for [GitHub Pages](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain), pointing to
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

**Comment by alexcrichton** [comment]
Ok, I've moved those records to AWS and it should be set up. The nameservers have been updated to AWS as well. Let me know if anything is awry!

**Comment by Mark-Simulacrum** [comment]
Okay, I've moved this repository over to rust-lang and @upsuper is still a collaborator. I didn't explicitly add anyone else (@nikomatsakis should have access as an org owner). We probably want to create a rust-lang/team team that's sync'd to GH which has access. Since we've moved over though and the site seems to be working, I'm going to give this issue a close.

**Comment by upsuper** [comment]
@alexcrichton Hey, recently I received an email from GitHub every day when areweasyncyet gets build, it says:
> The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site.

So I checked the DNS of the domain, it shows that
```
areweasyncyet.rs.	300	IN	A	185.199.111.153
areweasyncyet.rs.	300	IN	A	192.30.252.153
areweasyncyet.rs.	300	IN	A	192.30.252.154
areweasyncyet.rs.	300	IN	A	185.199.108.153
areweasyncyet.rs.	300	IN	A	185.199.109.153
areweasyncyet.rs.	300	IN	A	185.199.110.153
```

I'm supposing that "outdated IP address" may refer to the `192.30.252.{153,154}`. Could you remove them?

**Comment by alexcrichton** [comment]
Done!

**Comment by upsuper** [comment]
Thanks!

**Comment by upsuper** [comment]
@alexcrichton It seems the two A records came back, and GitHub starts sending me email to complain about it again. Any idea what happened there?

**Comment by alexcrichton** [comment]
@pietroalbini can you take care of this? I don't know how to use terraform myself and I think it's overwriting manual changes.

**Comment by pietroalbini** [comment]
I'll take a look tomorrow.

**Comment by pietroalbini** [comment]
Updated the DNS on the Terraform side.

**Comment by upsuper** [comment]
@pietroalbini Thanks!
