### ISSUE TITLE
CI:  Enable Github Pages from Actions

### ISSUE THREAD

**Issue by Orhideous** [rust-lang/areweasyncyet.rs#39]
To make pages work relevant setting on
https://github.com/rust-lang/areweasyncyet.rs/settings/pages should be `Source: GitHub Actions`

![image](https://user-images.githubusercontent.com/2265184/205637938-bed1313e-1af0-422f-8d70-19803055b25f.png)

**Comment by upsuper** [comment]
I don't have the permission to change this. I have reached out to the infra team for help.

**Comment by upsuper** [comment]
Thanks for updating the setting, @pietroalbini. It's working now.
